# Generated by Django 4.2.5 on 2023-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hngTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hngslack',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
