# Generated by Django 4.2.5 on 2023-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hngTasks', '0002_alter_hngslack_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hngslack',
            name='current_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
