# Generated by Django 4.2.5 on 2023-09-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hngTasks', '0003_alter_hngslack_current_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hngslack',
            name='utc_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
