# Generated by Django 4.2.5 on 2023-09-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hngTasks', '0004_alter_hngslack_utc_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HNGSLack',
        ),
    ]
